[package]
name = "variables"
version = "2.3.4"
authors = ["Ben Villalobos <4691428+BenVillalobos@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
