[package]
name = "imgproc"
version = "0.1.0"
authors = ["Ben Villalobos <4691428+BenVillalobos@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.23.12"
num-complex = "0.3.1"
clap = "2.33.3"